import java.util.*;
public class FindingMotif {
  public static void main( String[] args ) {
    String text = "CTCAGATTTCAACCTTCAGGGTGATTTCAGCGATTTCAAATGGATTTCAGATTTCACGTGATTTCAGATTTCAGATTTCAGGCTGATTTCACGTGGATTTCACTATAGATTTCAGTGATTTCAAGATTTCAACTACAAGACGATTTCAGATTTCAGCCGATTTCAGATTTCAGGGATGGGGATTTCATGATTTCATCCTGATTTCATCTAGATTTCAGATTTCACTTCCGGACGGCCAAGAGATTTCAGATTTCAACAGTCCTCCCTCTCGTATGATTTCAGATTTCAGATTTCAGGATTTCAAATGAAGACACGATTTCACGGGATTTCAGGCGTCTCCGATTTCAGATTTCATATCGCACTGTTGATTTCATCGATTTCAAGAGATTTCAAGCGCCGATTTCACAGGATTTCAGATTTCAAGATTTCACGCGTTACGATTTCAAGATTTCAGATTTCAGTAGGAAGATTTCAAAACTAGTGATTTCAGATTTCAGATTTCATGCAGGGGATTTCAACCGTATGCAAGATTTCATCATGGATTTCATGATTTCACGTAGGATTTCAGATTTCAGATTTCAGAGATTTCACCCGATTTCAGATTTCAGATTTCATGATTTCACCGATTTCAGATTTCATGATTTCATGATTTCAGATTTCAGATTTCAGATTTCAACGATTTCAAAGATTTCATGATTTCATGATTTCACACCGGATTTCAAGATTTCAGATTTCAATTAGTATTGATTTCAAGATTTCACTGAGATTTCAGGACTTCAGATTTCAATTTGATTTCACGATTTCATGATTTCACAGATTTCACGCGAGATTTCATGATTTCAGATTTCAGATTTCATCTATGATTTCATGCTTGGAGATAATGCGGATTTCACGATTTCAGATTTCACGGATTTCACAGATTTCACCGATGATTTCAGATTTCATGATTTCAGAAATTAGATTTCACGATTTCAGATTTCA";
    String motif = "GATTTCAGA";
    ArrayList<Integer> out = motifFind(text,motif);
    for(int i = 0; i < out.size(); ++i) {
      System.out.print(out.get(i) + " ");
    }
  }
  
  public static ArrayList<Integer> motifFind( String text, String motif ) {
    ArrayList<Integer> out = new ArrayList<>();
    for(int i = 0; i <= text.length() - motif.length(); ++i) {
      String window = text.substring(i,i+motif.length());
      if(window.equals(motif)) {
        out.add(i+1);
      }
    }
    return out;
  }
}