public class CountingDNANucleotides {
  public static void main( String[] args ) {
    String dna = "GAGTGTTATGCTCCAGGTGTTCTTTTGCCCCGGTCTGACCACTGTCCATTTGCCTCAGGGGTTGAAGGATTTAGCCAGCTACCCCCAGGGCCGTGCGATGTAGAGGGCTCATGCGAAAATGTTTATTAACCCCATTAGGACAGGGCTGGGTACTAATAAGTTCAGACTTATAACAAAATGCGCACCTGTTTCTAAGGGTATTGTCTGACGAGTATGACGCCCGTCGAAAGCATACATATTTTAACGGGGAAACCCGCCAGATTTAAACCGGTCGTTCCGGCACGGTCTGTCCCCTAAAATCCATCAGACAGTATAGTTGTTAGGTCTGGAGTTAGGAAGTGGTCCTCTTTAGCTAATTCTACCTCATTGGAAACAGTCTCTCAAAAGTGTCCCAATCCAGGAAGTGGCAAACACTTTGCTGTCTTTCGCTGACACATTGAAAGTCGTCGCCTCGACTGACAAACCCGTGATCGAGGTTTTCCGACAGGGTATGTTACGCTCCGGTGGCCGGATGAGCCGTCCGATTGGGCCAATGTGGATGAGGCATTGAAGCTCCAGTAATTCACGAGCCTGCGCCAACGGCCGGGCTTGACCTGCGTAGCCGGGCATCTAATAGGTCGGTAAGCACGGTTATTTTATGAAGCGTTAGAAGGTCGAGTGCCTGTCGGTACGAATTGGGGCATTTACCGACATAGGTTAGTTGATACTCCGGTCAAACGGTCATGAGGCAGGAGAGCTTTGACACCTCCATACTTAGCGTCGATGCTTCCCCCTCAATAGCACTACAGTTACCAATAGAGAGGGCCTCATCATAAGAAATAACCTCCAATATCAATAACG";
    int[] c = countNucleotides(dna);
    System.out.print(c[0]+" "+c[1]+" "+c[2]+" "+c[3]);
  }
  
  public static int[] countNucleotides( String dna ) {
    dna = dna.toUpperCase();
    int[] count = new int[4];
    for(int i = 0; i < dna.length(); ++i) {
      char c = dna.charAt(i);
           if(c == 'A') { ++count[0]; }
      else if(c == 'C') { ++count[1]; }
      else if(c == 'G') { ++count[2]; }
      else if(c == 'T') { ++count[3]; }
    }
    return count;
  }
}