import java.util.*;
public class CalculatingProteinMass {
  public static HashMap<Character,Double> aaToMass = new HashMap<>();

  public static void main( String[] args ) {
    String protein = "RKGGPNYVIAVSVIWEPRLYVKGELGTLLWKRSNFDVWKKFNQVRAPYKPIKCVAWDHEKHYIAAYRARYFVNNGCKFGKSQALIHGYVPGQIFEPANMCQHECNHEREVGWTFTPWHLWMGDADKDFFCCQNWIKGRTHEMMGKWQVDPHDFSWGQNDRYYWRMIRHMPINAVQIQMHFHDDRPMNFNNCMICPFVDSKQCKYMCKQFIWPVMGPTMEHCTKIEYLTHCINHASSCYLFARNILPADFRRNIGWTACQGVTSDAFALLIRNLCGKCKQLWELGHNELCGPMAIARSSQFVQQATKACCVGFGILFPYMFCMIHIANRCVWYSECILFHSQRRQPENPLEGGPVFFRIGSQHKSDLSWQAFPPWTGIWTAGEIWEIGVTPSFCCENQAPSHWMVDNTHCKWDWPSYNDMLRKWSQLKINDQKGCHGKLIAQCGDKETQVQAKPAIWCFCRKIACIKPNYHGQPCCGIPQSSTDPCWMEAYQWSWGTWWHYDRLCFNKHVEHIQQGYAIFLLRGVTNTIRRKVKDMYPYSSCTQHAYLWHFTMLMRNKGDGWVVADWLRAYASTLIYETCHPYFMYLDLIFQSKQYPGNRPHDMVYAHIPVFCYFDPNYAYFNSMAYQDTWKEPTSETITQDIKARHPCTWHETLGGGRSIVMDLYSERTSHFWIVQGYVTGKHKQMGFGTMQVKYGLYIHPEQTVHRWELWMMEHGIWRYWHPFTNEYWLRELRKKSEEIKFKKMDAKTVKYERKRFTGPNACWFCQQFLWHCTPKAFNMKFMRSWWMVECKGVLIHKGEAHVIFLPQKQIYYECPLPCVHYMKPKAANNPHDAVKVTHNPGLYVNKDWGATAMWHAAPIYPAFYVDGPMGNKDNNMHWCIMLTGDWHFLTGTESFEWG";
    initAAtable();
    System.out.println(proteinToMass(protein));
  }
  
  public static double proteinToMass( String protein ) {
    double sum = 0;
    for(int i = 0; i < protein.length(); ++i) {
      sum += aaToMass.get(protein.charAt(i));
    }
    return sum;
  }
  
  public static void initAAtable() {
    aaToMass.put('A',71.03711);
    aaToMass.put('C',103.00919);
    aaToMass.put('D',115.02694);
    aaToMass.put('E',129.04259);
    aaToMass.put('F',147.06841);
    aaToMass.put('G',57.02146);
    aaToMass.put('H',137.05891);
    aaToMass.put('I',113.08406);
    aaToMass.put('K',128.09496);
    aaToMass.put('L',113.08406);
    aaToMass.put('M',131.04049);
    aaToMass.put('N',114.04293);
    aaToMass.put('P',97.05276);
    aaToMass.put('Q',128.05858);
    aaToMass.put('R',156.10111);
    aaToMass.put('S',87.03203);
    aaToMass.put('T',101.04768);
    aaToMass.put('V',99.06841);
    aaToMass.put('W',186.07931);
    aaToMass.put('Y',163.06333);
  }
}