public class DNAtoRNA {
  public static void main( String[] args ) {
    String dna = "CGTTTTGGTTCTAACCGATCCGCCCATAGGTGAGAGAAGAACTCTCGTGCTCAGTGACGTGTATGAAGGATTTGCATGTGATGGCCTGCGACTCATTTAAAATCATGTACTAAGTTCGCCGGATAACCCGCAGAAGTTACAACCCAAATTTCGTCGTTGGTATGGAAGAAACCTGTTTCGCAGAAGGCTAACTCTTGCCGCCCTTTATGAGGATTTACTGGCTTTGCGACCTGTATGCATAGGTTAATTTGCGACGGGGATGTGTTGAGAGGCAACGCTTTATACATAGTACACCGTTTTCGCAACCTCGATTTCGAGCTGCGACAGAACGACATCAAAACAAGGGGTTCGGGATGCCAGGAGCCGAGCGTCAGAAGAAAGCCGTCCATCAACAGCTTCAGAGGACTGGCTGAACAGTTCACTTTATACACACCGTGGTCTCCGTGGGGGCATATCCCTCGTAGTCCTCGAGAAAAACTGTTCAACACCGGCACAATGCCACGACAAATCCATTGTTACATTTCCGTCATGCGTCCATTAAGTACTCAAAGACTTACTCTCGACGATAGAATGAAACACAGTTCCCCTTTCAAGGTAAATTTTAGATGCATATTATCTAAGCTCGCGCCTCTACGTAACCCCCTAGAAGTACACTGGTGGTGTAAGAATATAGCGGATCCACCCGGCGTATCTCGGGTGGGTCGGAATACGCAGATAACTACTAGAAACCACTGCAGCGATAAAGCGTGGTCGCACCGTCCGTAAGGCAGTGCGCTCCTCTCTATAGATAGCATCAGAACCTGGAGCCCTCACTGTTAACCTCTACCACCGCATTGTATTGTCAGGGACTAATTTTCGGGGACGGATAGCGCAATGAACACCCGGATCTCGATTATGGCGAGCGAT";
    System.out.println(dnaToRna(dna));
  }
  
  public static String dnaToRna( String dna ) {
    String out = "";
    for(int i = 0; i < dna.length(); ++i) {
      char c = dna.charAt(i);
      if(c == 'T') {
        out += 'U';
      }
      else if(c == 't') {
        out += 'u';
      }
      else {
        out += c;
      }
    }
    return out;
  }
}