public class FindingSplicedMotif {
  public static void main( String[] args ) {
    String s = "TCTCGACTTTAATGAGAGTAACAACACTCTGCAGCGAACTTTTACCCCGGCTGAGTGGGAGTGCGCCTCGGGGGCCCCATCTCGCCACCACCGGGAAGCCATCGACCCAGCAGCCTTATTTGCCCCGCTACAATAACGTGATGTTAGCTGCATGGCTTCAGCGCGAGCATGCGCTCTGGTCGGCGACGACAGCCTTAAACTGTTTTGTAAGCCAGGTCCTCTACACTGTACGGGATGTACGATGCTGCCTTGTTCGTAAAGGCTCATGTGTTCACATAACGGCCACGCGCTGCGGCCTCGTAAAGAACGCCACTAGGAGCTTAGTGAGATTTACGAGGAGCCGGGGGCACGAGATCGCGGATGGTAGGGGGTTCAAGGCCATGTCATAAGGTTTAACGAAGCACTTCCTGCCGCGTTAACTGGCAACTCACCTTCAAGGCATAGCATTGGGCTATTACCTGCCGTCGTATGTGGGCCAGAGGGGGAGAGGGGGGCAGTAAGATATGTATTAAGTTACCCGTCTAAATACAGGTCCGCCCTCGCCAGCATTGGCAAAACCCTCGAATCTATCATTTGGTGGTCCGCGGACTGGACAGGGTGTGCCTGCGTCGTAGTTTAAGCTCTGCCAGAGGACCTCCAGTCTTTCATTATCGAAAAAATCTAATGCGATAGCAAAGAATTAACGGGAGTCAGTTCCAGTTCTTGGATCTCTTCGGTTCGACCGCGGTGCACGTCGTTCGAGTGAGGTGCGTTAAAGCCCGGGTAGCCCGTTGAGGCAGATACTGATTCTCTGAGCAAACGACGACGTAGCTACAAAAGTACCCAAGGCGGTTGCGAATGTACAAAAGAGGGCAACGTGCGACCACACTCCCCAGATAAAGGTTTTCGCAGTGTAAGATGCGTA";
    String t = "AACGGCGACCGCCTGTGACCTGGGCGAGCGGTTATCTGAAGCAAAGAGACAGGAATAACCGAGTCAACGATGCGC";
    int[] out = findSplicedMotif(s,t);
    for(int i = 0; i < out.length; ++i) {
      System.out.print((out[i]+1) + " ");
    }
  }
  
  public static int[] findSplicedMotif( String s, String t ) {
    int[] inds = new int[t.length()];
    inds[0] = s.indexOf(t.charAt(0));
    int add = 1;
    while(add < inds.length) {
      int ind = s.indexOf(t.charAt(add),inds[add-1]+1);
      inds[add] = ind;
      ++add;
    }
    return inds;
  }
}