public class ReverseComplement {
  public static void main( String[] args ) {
    String dna = "AGTGGTAGGGGGTACATGTTGAGGTCTTTAGCGGTGCAAACTGGGGTTCTGCGCATGCGTCAGAACGAACCTTCAGTCGATTCTGTAGATCAGGCCCCTTCTGGATACCGTGGCCTTTTGGCGGATTCACAGAACTCGGATGCAACAAGACCTCGACCACAATTCCGCTGGGAGAGTGGGCTTCTTAAGTGATGAGGTTAAAGAGGCCGCTGGGCGGCTTAAACCGTGGATATTCGACAGTTTAACAACATCTTCTGACGGTTTACTGGATTCTGGGGTGTGCAAAACACTCACTGCCGGTTGCGATGCATGCACATCCCCGGCTAAAGGTGCGACCTGGTGTCCACAGAGGACGTCTTTCGAACAGCTACACACAGTACATATTCAAAATGCTCCGACATGTAGTACACGGGAACTCACTAGTACGTGTCATCGTAGAGATCCGATCTTCATAGGCTGTTTACCACTTGCACTCGATCTAGCGACCTATTGATCGGGCCCTGACAAGACACCTCACTCCGCGTCATTTAACCCCGTGCCACGGGAGGACAAGATCCCCTCATAGGTCTCGCTATGAGGCGACCGGTACTTCAATCGTCACGCATTATGGTTCCCGGGCCCCATTTTTGGGCGCGAGGTCGGCGGCACCTAAGCACTCGATCCCCGGTATCCAGAACACCGAGTCGACAGGCCCTCTCTTAGAGCGCTTAGTGAGGAATACCCTAGCCGTTTCGAATTATTCATCGCTATACTCAGGGGACACAGGTAAGGTGGTCACTCTAAGCGGTGGCGTGTTCCGGTTTCATCATCTAACGCTCTTTACTAGCGTCTGCAAT";
    System.out.println(reverseComplement(dna));
  }
  
  public static String reverseComplement( String in ) {
    in = in.toUpperCase();
    String out = "";
    for(int i = in.length()-1; i >= 0; --i) {
      char c = in.charAt(i);
           if(c == 'A') { out += 'T'; }
      else if(c == 'T') { out += 'A'; }
      else if(c == 'C') { out += 'G'; }
      else if(c == 'G') { out += 'C'; }
    }
    return out;
  }
}